### ISSUE TITLE
TypeError: local_create_house() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Trinkle23897** [facebookresearch/EmbodiedQA#10]
After I prepared all the data as mentioned in `README.md` modified the `House3D/tests/config.json` file, I run the `train_nav.py` and it always gives me the error "TypeError: local_create_house() takes 2 positional arguments but 3 were given"

Specifically, 
```
Process Process-2:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
TypeError: local_create_house() takes 2 positional arguments but 3 were given
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train_nav.py", line 817, in train
    train_loader = EqaDataLoader(**train_loader_kwargs)
  File "/home/jiayi/EmbodiedQA/training/data.py", line 890, in __init__
    max_actions=max_actions)
  File "/home/jiayi/EmbodiedQA/training/data.py", line 224, in __init__
    self._load_envs(start_idx=0, in_order=True)
  File "/home/jiayi/EmbodiedQA/training/data.py", line 326, in _load_envs
    self.all_houses = pool.starmap(local_create_house, _args)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
TypeError: local_create_house() takes 2 positional arguments but 3 were given
```
Any help?

**Comment by LisaAnne** [comment]
Are you linking to the right house3d?  You should link to [this](https://github.com/abhshkdz/House3D/tree/0bbba101a997908df16eee02936a0b539adeb0c2) version.

**Comment by Trinkle23897** [comment]
Oh yes, I fix it but, during the training process the program sometimes throws an exception. Does it behave normally?
