### ISSUE TITLE
Errors running train_eqa.py

### ISSUE THREAD

**Issue by yuanlixian** [facebookresearch/EmbodiedQA#16]
Hi I encountered some problems during the training of `train_eqa.py`. The mode is set as "train"

Traceback (most recent call last):
  File "train_eqa_em.py", line 961, in <module>
    train(0, args, shared_nav_model, shared_ans_model)
  File "train_eqa_em.py", line 641, in train
    action = planner_prob.multinomial().data
TypeError: multinomial() missing 1 required positional arguments: "num_samples"`

The python is 3.7 from anaconda3. The torch version is 0.4.1.post2. 
Any suggestions on this error? Thanks!

**Comment by yuanlixian** [comment]
Added a parameter 1 solves the problem.
